### ISSUE TITLE
Flux calibration for cubes reduced with ORB3

### ISSUE THREAD

**Issue by r-nepton** [crhea93/LUCI#119]
The flux calibration is now attached as a separate array to the hdf5 file. The calibration need to be applied on the spectra before fitting if the cube is version3. 

Here is the needed block to apply the flux calibration. 

if self.has_flux_calibration() and self.is_level3():
            spec = spec.multiply(orb.core.Cm1Vector1d(
                self.params.flambda / self.dimz / self.params.exposure_time,
                self.get_base_axis(),
                params=self.params))
        return spec

**Comment by crhea93** [comment]
So to handle this we need a way to check if the cube is level 3. If so then we can execute the calibration. @r-nepton What is the exact operation that occurs to do the calibration?

**Comment by crhea93** [comment]
The SITELLE team (i.e. @r-nepton) will be changing this on the initial reduction side. Therefore, there is no longer any need to implement this in `LUCI`.
