### ISSUE TITLE
Deredshifting C1, C2, and C4 data

### ISSUE THREAD

**Issue by lyalcorn** [crhea93/LUCI#129]
I see that in LuciBase line 81 and 82 the spectra for z~0.25 objects using C1, C2, and C4 are deredshifted. This is causing errors in the velocity and broadening maps, which do not then have a redshift correction.

We should deredshift these spectra instead, and create a new training set and reference spectrum for C1, C2, and C4 assuming a redshifted Halpha line complex.

**Comment by crhea93** [comment]
I believe this has been fixed, no? @lyalcorn
