### ISSUE TITLE
Adding the filter transmission curve to the fit

### ISSUE THREAD

**Issue by r-nepton** [crhea93/LUCI#22]
Filter transmission are really good but should be accounted for and treated at the same time we fit the lines and the continuum. The files are available in orb/orb/data/Filter....hdf5 which contain the transmission % as a function of the wavenumber

**Comment by crhea93** [comment]
As per our discussion I will
- read in the filter curve
- interpolate it into the observations spectral axis 
- apply the curve on the observed spectrum by diving the spectrum by the transmission curve
- fit as usual

**Comment by crhea93** [comment]
Transmission filters have been added with a cutoff of 50%
