### ISSUE TITLE
Fitting error for large FOV

### ISSUE THREAD

**Issue by Louis-Simon-Guite** [crhea93/LUCI#24]
When fitting a large portion of the cube (about 8x8 arcmin when I tried), there seems to be a fitting error for the right side of the image.

**Comment by crhea93** [comment]
The command was:
`vel_map, broad_map, flux_map, chi2_fits = cube.fit_cube(["NII6583", "Halpha"], 'sinc', x_min = 290, x_max = 1775, y_min = 330, y_max = 1815, vel_rel = [1,1], sigma_rel = [1,1], binning =1)`

The resulting image looks like this: 
![image](https://user-images.githubusercontent.com/34322936/126183753-ea117df3-08e0-47fc-9e72-4cebb6cae0c9.png)


There appears to be an issue with the way `LUCI` is handling these larger regions. You can see some structure from the interferogram steps...
