### ISSUE TITLE
Issue when trying to perform sky subtraction

### ISSUE THREAD

**Issue by benjaminvigneron** [crhea93/LUCI#32]
There seems to be an issue when performing the sky subtraction process. The function `extract_spectrum_region` works perfectly with an already defined region file and gives proper fitting results. However, if I try to directly specify a background region with the function `extract_spectrum` and x-y coordinates, the fitting results I obtain are completely different.

**Comment by crhea93** [comment]
The x and y pixels had not been properly transposed for the `extract_spectrum` function as they had been for all other functions. This has been remedied :D

**Comment by crhea93** [comment]
Reopening because this problem has occurred again.
