### ISSUE TITLE
Modification of the fit_region function

### ISSUE THREAD

**Issue by benjaminvigneron** [crhea93/LUCI#38]
In order for the `fit_region` function to have a broader utility, it could be useful to let the user input the coordinates of the region to fit, in the case where the mask is already produced for a specific region of the cube.

Indeed, in the current form of the function, if a mask is already created as a fits file for a small region, the user must create an empty canvas array with the same dimensions as the cube, then the user has to place the mask at the true position of the target structure in the cube. 

This can prove itself to be tricky especially when the fit will be binned, because the mask will not be linked to the cube, which means that the user must preemptively notice that the empty canvas array will need to have the same dimensions as the final binned cube. 

Finally, if the mask is a fits file, the user will have to save it as a npy file, which is something that could be directly handled in the function if need be. Here are some code example of what the user need to do in the specific case where the final fit will be binned 2x2 for the `fit_region` function to work correctly : 

`canvas = np.zeros((1024, 1032))

mask = fits.open('/home/carterrhea/Documents/Benjamin/NGC1275_masked_Luci_binned_mask.fits')

mask = mask[0].data

canvas[395:705,370:765]=mask.T

mask = canvas.astype(bool)

np.save('mask', mask)`

**Comment by crhea93** [comment]
Excellent issue. I will look into adding the regions coordinates (or bounding box) as a first step.

**Comment by crhea93** [comment]
@benjaminvigneron Are you still looking into this?

**Comment by crhea93** [comment]
I am closing this for now.
