### ISSUE TITLE
Astrometry error + transposed output for SNR map 

### ISSUE THREAD

**Issue by Louis-Simon-Guite** [crhea93/LUCI#48]
When using the function cube.create_snr_map( ), the output array is transposed relative to the cube and the astrometry coordinates are not the right ones.

The resulting array looks like:
![snr_map](https://user-images.githubusercontent.com/78374248/133005714-1f83dd5e-c165-4c8a-ad22-9b8e377c2df5.PNG)

instead of this for the orientation of the raw cube
![snr_map2](https://user-images.githubusercontent.com/78374248/133005735-69986cc2-7524-4f2a-920c-188e650e1c5a.PNG)

**Comment by crhea93** [comment]
The output was transposed -- I forgot to get rid of this when we did the other updates. IT has been fixed!
