### ISSUE TITLE
Data for Examples

### ISSUE THREAD

**Issue by crhea93** [crhea93/LUCI#60]
Determine how best to help users get the data for the examples. Also include better instructions. 
Include background and region file.

**Comment by crhea93** [comment]
I've also changed the data :D It now is only 860 MB and requires a simple copy and paste into the terminal. Can we close this? @jgcovi

**Comment by jgcovi** [comment]
yayyy let me look at how it works, but if the data is smaller and more easily available (ie. **example** data) then yeah, I think that constitutes as closed
