### ISSUE TITLE
Add progress bar to `create_deep_image`

### ISSUE THREAD

**Issue by jgcovi** [crhea93/LUCI#61]
For consistency with other functions processing the dataset, a progress bar should be added to any other functions which may take time to process. 

Known to be missing this bar is `create_deep_image`.

**Comment by crhea93** [comment]
Also need to add this to `create_snr_map`

**Comment by crhea93** [comment]
Added tqdm wrapper to the outer loop of `create_snr_map`

**Comment by crhea93** [comment]
I broke up the np.sum funciton to work on individual chunks so that I could add a progressbar to `create_deep_image`.

**Comment by jgcovi** [comment]
Nice - as long as it shows progress for anything that takes longer than a couple of seconds, you're golden
