### ISSUE TITLE
Clean up Examples notebooks

### ISSUE THREAD

**Issue by jgcovi** [crhea93/LUCI#62]
Clean up the examples notebooks to ease the burden on the user as they first begin to use `LUCI`. 
Things to be done include (but are not limited to):
- make sure file and folder paths are properly appended to the project repo path
- consider using os.path as the default to get the user's current directory and remove the need to add it
- Increased explanation on functionality and results - I will be a good test user for this piece to know if more info should be there :)

**Comment by crhea93** [comment]
Will do! The examples were intended for people who already have a fair amount of familiarity with SITELLE and the results, so I will work on rewording them.

**Comment by crhea93** [comment]
I've changed the example data to be even easier! Is that what you had in mind? @jgcovi

**Comment by jgcovi** [comment]
taking a look

**Comment by crhea93** [comment]
@jgcovi How are they looking?

**Comment by jgcovi** [comment]
I think the main example notebook looks good now. Easy to get the data and I can follow it pretty well. If anything, the graph might need to be cleaned up since it's cutting off the title and I can't seem to fix it directly from the figsize or anything, but it's not detrimental. We can close this
